# Configuration sops pour learnix
# Documentation: https://github.com/Mic92/sops-nix
#
# Configuration avec CLÉ PARTAGÉE (plus simple pour un homelab)
# La même clé est utilisée pour tous les hosts

# Règles de création pour chaque fichier de secrets
creation_rules:
  # Secrets pour l'hôte mimosa (serveur web)
  - path_regex: secrets/mimosa\.yaml$
    key_groups:
      - age:
          # Clé age partagée (générée sur le Mac, copiée sur les VMs)
          # Localisation : ~/.config/sops/age/nixos-shared-key.txt (Mac)
          #                /var/lib/sops-nix/key.txt (VMs)
          - &shared age1nt3ly627s6eqcv97zyw3n489gh7nt2jlrq6mfhucct8wq4lgku6saynhhw

  # Secrets pour l'hôte magnolia (infrastructure Proxmox)
  - path_regex: secrets/magnolia\.yaml$
    key_groups:
      - age:
          # Même clé partagée que mimosa
          - *shared

  # Secrets pour l'hôte whitelily (VM n8n automation)
  - path_regex: secrets/whitelily\.yaml$
    key_groups:
      - age:
          # Même clé partagée
          - *shared

  # Secrets communs (Tailscale OAuth, etc.)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *shared
