# Configuration sops pour learnix
# Documentation: https://github.com/Mic92/sops-nix
#
# Configuration avec CLÉ PARTAGÉE (plus simple pour un homelab)
# La même clé est utilisée pour tous les hosts

# Règles de création pour chaque fichier de secrets
creation_rules:
  # Secrets pour l'hôte jeremie-web
  - path_regex: secrets/jeremie-web\.yaml$
    key_groups:
      - age:
          # Clé age partagée (générée sur le Mac, copiée sur les VMs)
          # Localisation : ~/.config/sops/age/nixos-shared-key.txt (Mac)
          #                /var/lib/sops-nix/key.txt (VMs)
          - &shared age1nt3ly627s6eqcv97zyw3n489gh7nt2jlrq6mfhucct8wq4lgku6saynhhw

  # Secrets pour l'hôte proxmox
  - path_regex: secrets/proxmox\.yaml$
    key_groups:
      - age:
          # Même clé partagée que jeremie-web
          - *shared
