name: Gitea Actions Demo
run-name: ${{ gitea.actor }} teste le runner
on: [push]

jobs:
  explore-gitea-actions:
    runs-on: ubuntu-latest
    env:
      GITHUB_SERVER_URL: http://100.96.250.43:3000
      GITEA_SERVER_URL: http://100.96.250.43:3000
    steps:
      - run: echo "Le job a ete declenche automatiquement."
      - run: echo "Ce job tourne sur un serveur ${{ runner.os }} heberge par Gitea."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          github-server-url: http://100.96.250.43:3000
      - run: echo "Le statut est ${{ job.status }}."
