
[metadata]
name = "git-repos"
requirements = [ "fd", "git" ]
description = "Select from local git repositories (fast)."

[source]
command = "fd -g .git -H -t d -d 8 --prune ~/Development -E node_modules -E .cache -E .pnpm-store -E .npm -E .yarn --exec dirname '{}'"
display = "{split:/:-2}/{split:/:-1}"

[preview]
command = "cd '{}'; git --no-pager log -n 60 --oneline --decorate --graph --color=always 2>/dev/null || true"

