"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    # Trash (without confirmation)
    { on = [ "d" ], run = "remove --force", desc = "Envoyer a la corbeille sans confirmation" },

    # Diff with hovered file
    { on = [ "<C-d>" ], run = "plugin diff", desc = "Diff the selected with the hovered file" },

    # Toggle preview pane
    { on = [ "T", "p" ], run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },

    # Maximize preview pane
    { on = [ "T", "m" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },

    # Smart filter
    { on = [ "F" ], run = "plugin smart-filter", desc = "Smart filter" },

    # Open shell here
    { on = [ "!" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

    # Compress with ouch
    { on = [ "C" ], run = "plugin ouch", desc = "Compress with ouch" },

    # Rotate images clockwise
    { on = [ ">" ], run = [
        'shell "for file in "$@"; do magick "$file" -rotate 90 "${file%}"; done" --confirm',
        "refresh",
    ], desc = "Rotate selected images clockwise" },

    # Convert to PNG
    { on = [ "P", "p" ], run = [
        'shell "for file in "$@"; do magick "$file" "${file%.*}.png"; done" --confirm',
        "refresh",
    ], desc = "Convert selected images to PNG" },

    # Convert to JPEG 75%
    { on = [ "P", "j" ], run = [
        'shell "for file in "$@"; do magick "$file" -quality 75 "${file%.*}.jpg"; done" --confirm',
        "refresh",
    ], desc = "Convert selected images to JPEG with 75% quality" },

    # Rotate images counter-clockwise
    { on = [ "<" ], run = [
        'shell "for file in "$@"; do magick "$file" -rotate -90 "${file%}"; done" --confirm',
        "refresh",
    ], desc = "Rotate selected images counter-clockwise" },
]
