name: Build QCOW2 image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Build QCOW2 image
        run: |
          mkdir -p out
          nix run github:nix-community/nixos-generators -- \
            --format qcow \
            --flake .#nixos \
            -o ./out/nixos.qcow2

      - name: Upload QCOW2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-qcow2
          path: out/nixos.qcow2
