name: Build QCOW2 image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build QCOW2 image
        run: |
          mkdir -p out
          nix --accept-flake-config run github:nix-community/nixos-generators -- \
            --format qcow \
            --flake .#nixos-qcow \
            -o ./out/nixos.qcow2 \
            --show-trace

      - name: Upload QCOW2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-qcow2
          path: out/nixos.qcow2
