name: Build QCOW2 image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # Vous pouvez activer/désactiver les outils à supprimer
          # Ici on supprime les plus gros consommateurs d'espace
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          swift: true
          go: true
          java: true


      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build QCOW2 image
        run: |
          mkdir -p out
          nix run github:nix-community/nixos-generators -- \
            --format qcow \
            --flake .#nixos \
            -o ./out/nixos.qcow2

      - name: Upload QCOW2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-qcow2
          path: out/nixos.qcow2
