name: Build Proxmox QCOW2 image (UEFI + systemd-boot)

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          swift: true
          go: true
          java: true

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Use Cachix (pull & push)
        uses: cachix/cachix-action@v14
        with:
          name: jeremiealcaraz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build QCOW2 image for Proxmox
        run: |
          mkdir -p out
          nix --accept-flake-config run github:nix-community/nixos-generators -- \
            --format qcow \
            --flake .#proxmox \
            -o ./out/nixos-proxmox.qcow2 \
            --show-trace


      - name: Upload QCOW2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-proxmox-qcow2
          path: |
            out/nixos-proxmox.qcow2
            out/nixos-proxmox.qcow2.zst

      - name: Generate checksum
        run: |
          cd out
          sha256sum nixos-proxmox.qcow2 > nixos-proxmox.qcow2.sha256
          sha256sum nixos-proxmox.qcow2.zst > nixos-proxmox.qcow2.zst.sha256

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: out/*.sha256